export const planetList = [
  {
    planetRadius: 3,
    path: "../../assets/mercurymap.jpg",
    x: 80,
    y: 0,
    z: 0,
    hasRing: false,
    resistance: 0,
  },
  {
    planetRadius: 3,
    path: "../../assets/venusmap.jpg",
    x: 100,
    y: 0,
    z: 0,
    hasRing: false,
    resistance: 1,
  },
  {
    planetRadius: 4,
    path: "../../assets/earthmap.jpg",
    x: 120,
    y: 0,
    z: 0,
    hasRing: false,
    resistance: 1,
  },
  {
    planetRadius: 5,
    path: "../../assets/marsmap.jpg",
    x: 140,
    y: 0,
    z: 0,
    hasRing: false,
    resistance: 2,
  },
  {
    planetRadius: 8,
    path: "../../assets/jupitermap.jpg",
    x: 160,
    y: 0,
    z: 0,
    hasRing: true,
    radius: 10,
    resistance: 3,
  },
  {
    planetRadius: 7,
    path: "../../assets/saturnmap.jpg",
    x: 180,
    y: 0,
    z: 0,
    hasRing: true,
    radius: 9,
    resistance: 4,
  },
  {
    planetRadius: 6,
    path: "../../assets/uranusmap.jpg",
    x: 190,
    y: 0,
    z: 0,
    hasRing: false,
    resistance: 5,
  },
  {
    planetRadius: 3,
    path: "../../assets/neptunemap.jpg",
    x: 200,
    y: 0,
    z: 0,
    hasRing: false,
    resistance: 6,
  },
];
