export const planetList = [
  {
    planetRadius: 3,
    path: "../../assets/mercurymap.jpg",
    x: 80,
    y: 10,
    z: 0,
    hasRing: false,
    resistance: 0,
    color: 0xa0a0a0,
  },
  {
    planetRadius: 3,
    path: "../../assets/venusmap.jpg",
    x: 100,
    y: 100,
    z: 0,
    hasRing: false,
    resistance: 1,
    color: 0xf0e8d8,
  },
  {
    planetRadius: 4,
    path: "../../assets/earthmap.jpg",
    x: 120,
    y: 120,
    z: 0,
    hasRing: false,
    resistance: 1,
    color: 0x007bff,
  },
  {
    planetRadius: 5,
    path: "../../assets/marsmap.jpg",
    x: 140,
    y: 400,
    z: 0,
    hasRing: false,
    resistance: 2,
    color: 0xc7543f,
  },
  {
    planetRadius: 8,
    path: "../../assets/jupitermap.jpg",
    x: 160,
    y: 0,
    z: 0,
    hasRing: true,
    radius: 10,
    resistance: 3,
    color: 0xc2b280,
  },
  {
    planetRadius: 7,
    path: "../../assets/saturnmap.jpg",
    x: 180,
    y: 0,
    z: 0,
    hasRing: true,
    radius: 9,
    resistance: 4,
    color: 0xc2b280,
  },
  {
    planetRadius: 6,
    path: "../../assets/uranusmap.jpg",
    x: 190,
    y: 0,
    z: 0,
    hasRing: false,
    resistance: 5,
    color: 0x2e8b57,
  },
  {
    planetRadius: 3,
    path: "../../assets/neptunemap.jpg",
    x: 200,
    y: 0,
    z: 0,
    hasRing: false,
    resistance: 6,
    color: 0x2b3e5b,
  },
];
